//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarCitizen.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarCitizen.Json.ApiResponses", typeof(ApiResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///          &quot;id&quot;: &quot;314&quot;,
        ///          &quot;status&quot;: &quot;P&quot;,
        ///          &quot;time_modified&quot;: &quot;2018-01-27 01:36:42&quot;,
        ///          &quot;type&quot;: &quot;SINGLE_STAR&quot;,
        ///          &quot;name&quot;: &quot;Stanton&quot;,
        ///          &quot;code&quot;: &quot;STANTON&quot;,
        ///          &quot;position_x&quot;: &quot;49.53471800&quot;,
        ///          &quot;position_y&quot;: &quot;-2.63396450&quot;,
        ///          &quot;position_z&quot;: &quot;16.47529200&quot;,
        ///          &quot;description&quot;:
        ///            &quot;While the UEE still controls the rights to the system overall, the four planets themselves were sold by the government to four megacorporations making them [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StantonJson {
            get {
                return ResourceManager.GetString("StantonJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StarMapBootstrap {
            get {
                object obj = ResourceManager.GetObject("StarMapBootstrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
